// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Block       = require("bs-platform/lib/js/block.js");
var Curry       = require("bs-platform/lib/js/curry.js");
var React       = require("react");
var Styles$Md   = require("../types/Styles.js");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");

var component = ReasonReact.statelessComponent("PostEditor");

var style = Styles$Md.css(/* :: */[
      /* Width */Block.__(0, ["100%"]),
      /* :: */[
        /* Height */Block.__(1, ["100%"]),
        /* [] */0
      ]
    ]);

var textareaStyle = Styles$Md.css(/* :: */[
      /* Padding */Block.__(7, ["80px"]),
      /* [] */0
    ]);

function make(post, updatePost, _) {
  var onChange = function ($$event) {
    return Curry._1(updatePost, $$event.target.value);
  };
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return React.createElement("div", {
                  className: "editor",
                  style: style
                }, React.createElement("textarea", {
                      style: textareaStyle,
                      value: post.text,
                      onChange: onChange
                    }));
    });
  return newrecord;
}

exports.component     = component;
exports.style         = style;
exports.textareaStyle = textareaStyle;
exports.make          = make;
/* component Not a pure module */
