// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/lib/js/src/jest.js");

describe("Expect", (function () {
        return Jest.test("true to be true", (function () {
                      return Jest.Expect[/* toBe */2](/* true */1, Jest.Expect[/* expect */0](/* true */1));
                    }));
      }));

/*  Not a pure module */
