// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var ReasonReact   = require("reason-react/src/ReasonReact.js");
var ReactMarkdown = require("react-markdown");

function make(source, children) {
  return ReasonReact.wrapJsForReason(ReactMarkdown, {
              source: source
            }, children);
}

exports.make = make;
/* ReasonReact Not a pure module */
