// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Curry       = require("bs-platform/lib/js/curry.js");
var React       = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");

var component = ReasonReact.statelessComponent("PostEditor");

var textareaStyle = {
  height: "400px",
  width: "100%"
};

function make(post, updatePost, _) {
  var onChange = function ($$event) {
    return Curry._1(updatePost, $$event.target.value);
  };
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return React.createElement("div", undefined, React.createElement("textarea", {
                      style: textareaStyle,
                      value: post.text,
                      onChange: onChange
                    }));
    });
  return newrecord;
}

exports.component     = component;
exports.textareaStyle = textareaStyle;
exports.make          = make;
/* component Not a pure module */
