// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';


function setText(text, post) {
  return Object.assign(post, {
              text: text
            });
}

function setTitle(title, post) {
  return Object.assign(post, {
              title: title
            });
}

function addTag(tag, post) {
  return Object.assign(post, {
              tags: post.tags.concat(tag)
            });
}

exports.setText  = setText;
exports.setTitle = setTitle;
exports.addTag   = addTag;
/* No side effect */
