// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var List       = require("bs-platform/lib/js/list.js");
var ReactDOMRe = require("reason-react/lib/js/src/ReactDOMRe.js");

function parseStyleType(d) {
  switch (d.tag | 0) {
    case 0 : 
        return {
                width: d[0]
              };
    case 1 : 
        return {
                height: d[0]
              };
    case 2 : 
        return {
                minHeight: d[0]
              };
    case 3 : 
        return {
                display: d[0]
              };
    
  }
}

function combineStyles(s) {
  var parsed = List.map(parseStyleType, s);
  return List.fold_left(ReactDOMRe.Style[/* combine */0], { }, parsed);
}

exports.parseStyleType = parseStyleType;
exports.combineStyles  = combineStyles;
/* ReactDOMRe Not a pure module */
