// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var List       = require("bs-platform/lib/js/list.js");
var ReactDOMRe = require("reason-react/lib/js/src/ReactDOMRe.js");

function makeDisplay(d) {
  if (d !== 0) {
    return {
            display: "flex",
            flexDirection: "column"
          };
  } else {
    return {
            display: "flex"
          };
  }
}

function makePosition() {
  return {
          position: "fixed"
        };
}

function parseStyleType(d) {
  if (typeof d === "number") {
    return {
            flexGrow: "1"
          };
  } else {
    switch (d.tag | 0) {
      case 0 : 
          return {
                  width: d[0]
                };
      case 1 : 
          return {
                  height: d[0]
                };
      case 2 : 
          return {
                  minHeight: d[0]
                };
      case 3 : 
          return {
                  minWidth: d[0]
                };
      case 4 : 
          return makeDisplay(d[0]);
      case 5 : 
          return makePosition(d[0]);
      case 6 : 
          return {
                  margin: d[0]
                };
      case 7 : 
          return {
                  padding: d[0]
                };
      
    }
  }
}

function css(s) {
  var parsed = List.map(parseStyleType, s);
  return List.fold_left(ReactDOMRe.Style[/* combine */0], { }, parsed);
}

exports.makeDisplay    = makeDisplay;
exports.makePosition   = makePosition;
exports.parseStyleType = parseStyleType;
exports.css            = css;
/* ReactDOMRe Not a pure module */
