// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var React       = require("react");
var Markdown$Md = require("./Markdown.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");

var component = ReasonReact.statelessComponent("Article");

function make(post, _) {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return React.createElement("div", undefined, React.createElement("small", undefined, "Created at " + Date(post.createdAt)), React.createElement("br", undefined), React.createElement("small", undefined, "Updated at " + Date(post.updatedAt)), ReasonReact.element(/* None */0, /* None */0, Markdown$Md.make(post.text, /* array */[])));
    });
  return newrecord;
}

exports.component = component;
exports.make      = make;
/* component Not a pure module */
