// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Block       = require("bs-platform/lib/js/block.js");
var Curry       = require("bs-platform/lib/js/curry.js");
var React       = require("react");
var Styles$Md   = require("./types/Styles.js");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");

var component = ReasonReact.statelessComponent("PostEditor");

var divStyles = Styles$Md.combineStyles(/* :: */[
      /* Display */Block.__(3, ["flex"]),
      /* :: */[
        /* Width */Block.__(0, ["100%"]),
        /* [] */0
      ]
    ]);

var textareaStyles = Styles$Md.combineStyles(/* :: */[
      /* Display */Block.__(3, ["flex"]),
      /* :: */[
        /* Width */Block.__(0, ["700px"]),
        /* [] */0
      ]
    ]);

function make(post, updatePost, _) {
  var onChange = function ($$event) {
    return Curry._1(updatePost, $$event.target.value);
  };
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return React.createElement("div", {
                  style: divStyles
                }, React.createElement("textarea", {
                      style: textareaStyles,
                      value: post.text,
                      onChange: onChange
                    }));
    });
  return newrecord;
}

exports.component      = component;
exports.divStyles      = divStyles;
exports.textareaStyles = textareaStyles;
exports.make           = make;
/* component Not a pure module */
