// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Block       = require("bs-platform/lib/js/block.js");
var React       = require("react");
var Styles$Md   = require("./types/Styles.js");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");

var component = ReasonReact.statelessComponent("Post");

var style = Styles$Md.css(/* :: */[
      /* Margin */Block.__(5, ["0"]),
      /* :: */[
        /* Padding */Block.__(6, ["0"]),
        /* [] */0
      ]
    ]);

function make(children) {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return React.createElement("div", {
                  style: style
                }, children);
    });
  return newrecord;
}

var $$default = ReasonReact.wrapReasonForJs(component, (function (props) {
        return make(props.children);
      }));

exports.component = component;
exports.style     = style;
exports.make      = make;
exports.$$default = $$default;
exports.default   = $$default;
exports.__esModule= true;
/* component Not a pure module */
